import { ThemeProvider } from '@mui/material/styles';
import theme, {primaryColor} from '../theme';
import NextTopLoader from 'nextjs-toploader';

export const metadata = {
  title: 'PV Dashboard',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <html lang="en">
          <body>
              <ThemeProvider theme={theme}>
                  <NextTopLoader color={primaryColor}/>
                  {children}
              </ThemeProvider>
          </body>
        </html>
  )
}
